export const COLUMN_MAPPING = {
  "EJERCICIO": "ejercicio",
  "INSTRUMENTO": "instrumento",
  "FECHA PAGO": "fechaPago",
  "DESCRIPCION": "descripcionDividendo",
  "SECUENCIA": "secuenciaEvento",
  "ISFUT": "acogidoIsfut",
  "ORIGEN": "origen",
  "FACTOR ACTUALIZACION": "factorActualizacion",

  // Factores 8 a 37
  "AJUSTE CAPITAL": "factor8",
  "RENTA DEVENGADA": "factor9",
  "RENTA PERCIBIDA": "factor10",
  "CORRECCION MONETARIA": "factor11",
  "GASTO RECHAZADO": "factor12",
  "CRÉDITO TOTAL": "factor13",
  "CRÉDITO PARCIAL": "factor14",
  "CAPITAL PROPIO": "factor15",
  "VALOR LIBRO": "factor16",
  "UTILIDAD REPARTIDA": "factor17",
  "DIFERENCIA TRIBUTARIA": "factor18",
  "REVALORIZACION ACCION": "factor19",
  "FACTOR20": "factor20",
  "FACTOR21": "factor21",
  "FACTOR22": "factor22",
  "FACTOR23": "factor23",
  "FACTOR24": "factor24",
  "FACTOR25": "factor25",
  "FACTOR26": "factor26",
  "FACTOR27": "factor27",
  "FACTOR28": "factor28",
  "FACTOR29": "factor29",
  "FACTOR30": "factor30",
  "FACTOR31": "factor31",
  "FACTOR32": "factor32",
  "FACTOR33": "factor33",
  "FACTOR34": "factor34"
};
